### ISSUE TITLE
Javascript Keywords as Props - Error

### ISSUE THREAD

**Issue by jvanderen1** [sveltejs/eslint-plugin-svelte3#152] opened 2021-12-19 22:48 UTC
There seems to be a re-occurring issue where you cannot properly use props which are named the same as Javascript keywords (i.e. `class`, `for`, etc.). It seems the best workaround is to simply use the `$$props` syntax.

In my case, I am trying to the use `for` and `class` prop inside my reusable `label` component:

```svelte
<label for={$$props.for} class={`block text-sm font-medium text-gray-700 ${$$props.class}`}>
  <slot />
</label>
```

However, when running `eslint .`, I received the following error on both these guys:

```shell
  1:13  error  '$$props' is not defined  no-undef
  1:76  error  '$$props' is not defined  no-undef
```

However, if I add the `<script>` tags at the top of the file, like so:

```svelte
<script></script>

<label for={$$props.for} class={`block text-sm font-medium text-gray-700 ${$$props.class}`}>
	<slot />
</label>
```

I receive no errors.

I am not sure what the svelte team can do as this seems like a language oversight, but I wish there was a way to easily extract these Javascript keyword-named props.

**Comment by dummdidumm** [comment] 2022-01-03 14:31
Possible duplicate of #148

**Closed** 2022-01-03 14:51 UTC
