### ISSUE TITLE
ParseError: Unexpected token

### ISSUE THREAD

**Issue by rondonjon** [sveltejs/eslint-plugin-svelte3#60] opened 2020-05-13 08:39 UTC
I am getting errors like this from the plugin on every file:

```
/home/xxx/yyy/src/App.svelte
  4:14  error  Unexpected token  ParseError
```

I use the @kaisermann [preprocessor](https://github.com/kaisermann/svelte-preprocess).

The error is always (and only) caused by the *first* explicit type in a .svelte file, e.g.:

```
  const x: X = {
```

Possibly a duplicate of #10 or #53

**Comment by Conduitry** [comment] 2020-05-13 11:26
This is indeed a duplicate of both of those issues.

**Closed by Conduitry** 2020-05-13 11:26 UTC
