### ISSUE TITLE
Re-opening: 'svelte3/svelte3' was not found (appears with eslint 7)

### ISSUE THREAD

**Issue by richardeschloss** [sveltejs/eslint-plugin-svelte3#59] opened 2020-05-09 01:15 UTC
eslint-plugin-svelte3 version: 2.7.3
eslint version: 7.0.0

Using the eslint config:

`.eslintrc.js` in project root. Project was scaffolded with `npx degit sveltejs/template`. 
```
module.exports = {
    parserOptions: {
      ecmaVersion: 2019,
      sourceType: 'module'
    },
    env: {
      es6: true,
      browser: true
    },
    plugins: [
      'svelte3'
    ],
    overrides: [
      {
        files: ['*.svelte'],
        processor: 'svelte3/svelte3'
      }
    ]
}
```

Result:
```
[Error - 5:55:08 PM] ESLint stack trace:
[Error - 5:55:08 PM] Error: ESLint configuration of processor in '.eslintrc.json#overrides[0]' is invalid: 'svelte3/svelte3' was not found.
```

**Comment by Conduitry** [comment] 2020-05-09 02:58
I can't reproduce this. I've cloned a new copy of the Svelte template, installed its dependencies, installed `eslint` (7.0.0) and `eslint-plugin-svelte3` (2.7.3), created that `.eslintrc.js` in the root, and run `npx eslint src/App.svelte`, and I have no errors.

**Comment by richardeschloss** [comment] 2020-05-09 04:00
Did you test in vscode or from the command line?

**Comment by Conduitry** [comment] 2020-05-09 11:52
Both.

**Comment by richardeschloss** [comment] 2020-05-09 19:23
I appreciate your patience. Please keep the issue open and I'll try to provide more information. I'm able to run the linter on the command line without issue. It's the eslint vscode extension that is encountering the error. I am on eslint extension 1.9.0 and vscode 1.35.1. Give me a few minutes to update those and see if upgrading resolves this.

**Comment by richardeschloss** [comment] 2020-05-09 20:04
Ok, found the issue. It might be worth documenting. So, ESLint's vscode extension had to be updated to latest **2.1.5** (which required updating VS code to **1.45.0**. 

As mentioned in issue threads, the following is required: 
```
{
  "eslint.validate": [
    "svelte"
  ]
}
```

Would it be alright if I submitted a PR with suggested doc changes? This information would be really useful in the README.md file. Especially since the [2019 blog](https://svelte.dev/blog/setting-up-your-editor) can get out of date and miss important details.

The other thing the blog mentions is the setting:
```
  "files.associations": {
    "*.svelte": "html"
  }
```

While that setting doesn't interfere with eslint-plugin-svelte3, it *does* interfere with the other svelte vs extensions. I had to remove that to allow the following vscode extensions to work: svelte-vscode, vscode-svelte-snippets, svelte-intellisense.

**Comment by Conduitry** [comment] 2020-05-15 09:43
Pretty much all of what you mention here is already in https://github.com/sveltejs/eslint-plugin-svelte3/blob/master/INTEGRATIONS.md#visual-studio-code apart from the minimum version requirement. If you know specifically between which two versions of the VSCode ESLint extension this started working, we could consider adding that, but I don't want to get too bogged down in that sort of stuff, because people generally hopefully have auto updates enabled in their editor.

Closing this in favor of #50 where ways to make the documentation clearer can be discussed.

**Closed by Conduitry** 2020-05-15 09:43 UTC
Labels: question

**Comment by richardeschloss** [comment] 2020-05-15 16:23
Ok. Sorry about that. I overlooked that section.
